### ISSUE TITLE
移动端 CatalogModal 可能出现双滚动条

### ISSUE THREAD

**Issue by mojimoon** [FishHawk/auto-novel#190]
这个问题的原因其实很简单，但确实不好解决。暂时放在这里了。

`CatalogModal.vue:118` 规定了 `max-height: 80vh`，但不一定扩展到这个高度：

```ts
  <c-modal
    style="min-height: 30vh; max-height: 80vh"
    content-style="overflow: auto;"
  >
```

而 `ChapterTocList.vue:183` 又是用 `80vh` 作为基准计算的：

```css
@supports (height: 100dvh) {
  .modal-virtual-list {
    max-height: calc(80dvh - 200px);
  }
}
@supports not (height: 100dvh) {
  .modal-virtual-list {
    max-height: calc(80vh - 200px);
  }
} 
```
